### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by vistafan12** [HoLLy-HaCKeR/custom-bancho#3]
fix

**Comment by holly-hacker** [comment]
If you can't describe your problem properly, I doubt you are the kind of person that should use this.

This repo is meant as a resource for other people that make custom servers. You should either get one that is more complete (such as ripple) or just play on one that is made by someone else.

**Comment by vistafan12** [comment]
Ok, thanks for the reply. Although I fixed this problem, osu! still I do not want to connect to Bancho.
